<a href="https://colab.research.google.com/github/abhish3k4/Deep-learning-Project/blob/main/A_1Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as ps
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [ ]:
scalar = torch.tensor(13)
scalar.item()

13

In [ ]:
scalar.ndim

0

In [ ]:
vector = torch.tensor([7,7])
vector
vector.ndim
vector.shape

torch.Size([2])

In [ ]:
matrix = torch.tensor([[2,3],[2,6]])
matrix

tensor([[2, 3],
        [2, 6]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]

tensor([2, 6])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1,2,4] ,[23,4,2] , [2,4,2]]])
TENSOR

tensor([[[ 1,  2,  4],
         [23,  4,  2],
         [ 2,  4,  2]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0,2]

tensor([2, 4, 2])

In [ ]:
###  Random Tensor

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6578, 0.3639, 0.7998, 0.8542],
        [0.4355, 0.7384, 0.2028, 0.9562],
        [0.2643, 0.0408, 0.3201, 0.2254]])

In [ ]:
RT = torch.rand(3,8)
RT

tensor([[0.6646, 0.4992, 0.6551, 0.7081, 0.7572, 0.8885, 0.5314, 0.3712],
        [0.4407, 0.3586, 0.7854, 0.2537, 0.5454, 0.4142, 0.1645, 0.3713],
        [0.6667, 0.7245, 0.8088, 0.5310, 0.3325, 0.1022, 0.9436, 0.3867]])

In [ ]:
RT.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3 , 224  , 224)) # height , width ,colour change
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
zeros  = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones , ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [ ]:
#Creating  range of tensors and tensors-like

In [ ]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_ten = torch.arange(start= 1 , end = 1000 , step = 200 )
one_to_ten

tensor([  1, 201, 401, 601, 801])

In [ ]:
# Creating tensors like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

Tensor Datatypes


In [ ]:
float_32_tensor = torch.tensor([3.0 , 6.0 ,9.0],
                               dtype = None,
                               device=None,
                               requires_grad=False)
float_32_tensor , float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)