<a href="https://colab.research.google.com/github/abhish3k4/Deep-learning-Project/blob/main/A_1Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import torch
import pandas as ps
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [43]:
scalar = torch.tensor(13)
scalar.item()

13

In [44]:
scalar.ndim

0

In [45]:
vector = torch.tensor([7,7])
vector
vector.ndim
vector.shape

torch.Size([2])

In [46]:
matrix = torch.tensor([[2,3],[2,6]])
matrix

tensor([[2, 3],
        [2, 6]])

In [47]:
matrix.ndim

2

In [48]:
matrix[1]

tensor([2, 6])

In [49]:
matrix.shape

torch.Size([2, 2])

In [50]:
TENSOR = torch.tensor([[[1,2,4] ,[23,4,2] , [2,4,2]]])
TENSOR

tensor([[[ 1,  2,  4],
         [23,  4,  2],
         [ 2,  4,  2]]])

In [51]:
TENSOR.ndim

3

In [52]:
TENSOR.shape

torch.Size([1, 3, 3])

In [53]:
TENSOR[0,2]

tensor([2, 4, 2])

In [54]:
###  Random Tensor

In [55]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8967, 0.7315, 0.3703, 0.3124],
        [0.8736, 0.3612, 0.3997, 0.4911],
        [0.1166, 0.7601, 0.1751, 0.6301]])

In [56]:
RT = torch.rand(3,8)
RT

tensor([[0.2060, 0.3913, 0.6621, 0.6474, 0.6904, 0.6310, 0.2021, 0.0709],
        [0.5136, 0.3026, 0.9222, 0.5012, 0.9900, 0.1789, 0.6378, 0.7946],
        [0.0939, 0.4584, 0.0598, 0.8837, 0.7811, 0.6038, 0.8639, 0.9115]])

In [57]:
RT.ndim

2

In [58]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3 , 224  , 224)) # height , width ,colour change
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [59]:
zeros  = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [60]:
ones = torch.ones(size=(3,4))
ones , ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [61]:
#Creating  range of tensors and tensors-like

In [62]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
one_to_ten = torch.arange(start= 1 , end = 1000 , step = 200 )
one_to_ten

tensor([  1, 201, 401, 601, 801])

In [64]:
# Creating tensors like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

Tensor Datatypes


In [65]:
float_32_tensor = torch.tensor([3.0 , 6.0 ,9.0],
                               dtype = None,
                               device=None,
                               requires_grad=False)
float_32_tensor , float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [66]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [67]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [68]:
int_32_tensor = torch.tensor([3,7,6] , dtype = torch.int32)
int_32_tensor

tensor([3, 7, 6], dtype=torch.int32)

# Getting information from tensors

1.Tensors not right datatype - to do get datatype from a tensor , can use tensor.dtype
2.Tensors not right shape - to get shape from a tensor , can use tensor.shape
3.Tensors not on the right device - to get device from a tensor , can use tensor.device                                           

In [69]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8712, 0.0776, 0.3903, 0.6288],
        [0.3521, 0.3527, 0.9041, 0.7853],
        [0.0908, 0.0286, 0.3686, 0.6377]])

In [70]:
#find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.8712, 0.0776, 0.3903, 0.6288],
        [0.3521, 0.3527, 0.9041, 0.7853],
        [0.0908, 0.0286, 0.3686, 0.6377]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device tensor is on : cpu


## Manipulation Tensors (tensor operations)

Tensor Opertions include:
* Additions
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [71]:
#Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [72]:
#Multiply Tensor by 10
tensor = tensor *10
tensor

tensor([10, 20, 30])

In [73]:
#Subtract 10
tensor - 10

tensor([ 0, 10, 20])

In [74]:
# Try Out PyTorch in-built Functions
torch.mul(tensor,10)

tensor([100, 200, 300])

In [75]:
torch.sub(tensor , 1000)

tensor([-990, -980, -970])

# Mattrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [76]:
# Element wise multiplication
print(tensor , "*" , tensor)
print(f"Equals : {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals : tensor([100, 400, 900])


In [77]:
#Matix Multiplication
torch.matmul(tensor , tensor)

tensor(1400)

In [81]:
tensor

tensor([10, 20, 30])

In [80]:
# Matrix Multiplication By Hand

1*1 + 2*2 + 3*3

14

In [82]:
# Time

value = 0
for i in range(len(tensor)):
  value += tensor[i] + tensor[i]
print(value)

tensor(120)


In [83]:
#Time
torch.matmul(tensor , tensor)

tensor(1400)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimesnions ** must match:
* (3,2) @ (3,2) wont work
* (2,3) @ (3,2) will work
* (3,2) @ (2,3) will work
@ = Multiplication

torch.matmul(torch.rand(3,2),torch.rand(3,2) Comon Mistake People used to do


2. The resulting matrix has the shape of the **outer dimensions**

(2,3) @ (3,2) --> (2,2)
(3,2) @ (2,3) --> (3,3)

In [84]:
tensor @ tensor

tensor(1400)

In [87]:
 torch.matmul(torch.rand(2,3) , torch.rand(3,2))

tensor([[0.6386, 1.0043],
        [0.5695, 0.4681]])