<a href="https://colab.research.google.com/github/abhish3k4/Deep-learning-Project/blob/main/A_2Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as ps
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [2]:
scalar = torch.tensor(13)
scalar.item()

13

In [3]:
scalar.ndim

0

In [4]:
vector = torch.tensor([7,7])
vector
vector.ndim
vector.shape

torch.Size([2])

In [5]:
matrix = torch.tensor([[2,3],[2,6]])
matrix

tensor([[2, 3],
        [2, 6]])

In [6]:
matrix.ndim

2

In [7]:
matrix[1]

tensor([2, 6])

In [8]:
matrix.shape

torch.Size([2, 2])

In [9]:
TENSOR = torch.tensor([[[1,2,4] ,[23,4,2] , [2,4,2]]])
TENSOR

tensor([[[ 1,  2,  4],
         [23,  4,  2],
         [ 2,  4,  2]]])

In [10]:
TENSOR.ndim

3

In [11]:
TENSOR.shape

torch.Size([1, 3, 3])

In [12]:
TENSOR[0,2]

tensor([2, 4, 2])

In [13]:
###  Random Tensor

In [14]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8640, 0.7171, 0.5512, 0.6030],
        [0.7720, 0.3219, 0.3898, 0.3906],
        [0.7201, 0.9521, 0.4778, 0.0617]])

In [15]:
RT = torch.rand(3,8)
RT

tensor([[0.7368, 0.3677, 0.7978, 0.1612, 0.8955, 0.3356, 0.2463, 0.7001],
        [0.5948, 0.8790, 0.4375, 0.3773, 0.3164, 0.1422, 0.9232, 0.4678],
        [0.2747, 0.6947, 0.9144, 0.7847, 0.5378, 0.9480, 0.7762, 0.0050]])

In [16]:
RT.ndim

2

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3 , 224  , 224)) # height , width ,colour change
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [18]:
zeros  = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones = torch.ones(size=(3,4))
ones , ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [20]:
#Creating  range of tensors and tensors-like

In [21]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
one_to_ten = torch.arange(start= 1 , end = 1000 , step = 200 )
one_to_ten

tensor([  1, 201, 401, 601, 801])

In [23]:
# Creating tensors like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

Tensor Datatypes


In [24]:
float_32_tensor = torch.tensor([3.0 , 6.0 ,9.0],
                               dtype = None,
                               device=None,
                               requires_grad=False)
float_32_tensor , float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [33]:
int_32_tensor = torch.tensor([3,7,6] , dtype = torch.int32)
int_32_tensor

tensor([3, 7, 6], dtype=torch.int32)

# Getting information from tensors

1.Tensors not right datatype - to do get datatype from a tensor , can use tensor.dtype
2.Tensors not right shape - to get shape from a tensor , can use tensor.shape
3.Tensors not on the right device - to get device from a tensor , can use tensor.device                                           

In [40]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7826, 0.1525, 0.6504, 0.1662],
        [0.1923, 0.4823, 0.0293, 0.0138],
        [0.4455, 0.7628, 0.8832, 0.7266]])

In [41]:
#find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.7826, 0.1525, 0.6504, 0.1662],
        [0.1923, 0.4823, 0.0293, 0.0138],
        [0.4455, 0.7628, 0.8832, 0.7266]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device tensor is on : cpu


## Manipulation Tensors (tensor operations)

Tensor Opertions include:
* Additions
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [58]:
#Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [64]:
#Multiply Tensor by 10
tensor = tensor *10
tensor

tensor([1000000, 2000000, 3000000])

In [66]:
#Subtract 10
tensor - 10

tensor([ 999990, 1999990, 2999990])

In [67]:
# Try Out PyTorch in-built Functions
torch.mul(tensor,10)

tensor([10000000, 20000000, 30000000])

In [78]:
torch.sub(tensor , 1000)

tensor([ 999000, 1999000, 2999000])