<a href="https://colab.research.google.com/github/abhish3k4/Deep-learning-Project/blob/main/A_2Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as ps
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [2]:
scalar = torch.tensor(13)
scalar.item()

13

In [3]:
scalar.ndim

0

In [4]:
vector = torch.tensor([7,7])
vector
vector.ndim
vector.shape

torch.Size([2])

In [5]:
matrix = torch.tensor([[2,3],[2,6]])
matrix

tensor([[2, 3],
        [2, 6]])

In [6]:
matrix.ndim

2

In [7]:
matrix[1]

tensor([2, 6])

In [8]:
matrix.shape

torch.Size([2, 2])

In [9]:
TENSOR = torch.tensor([[[1,2,4] ,[23,4,2] , [2,4,2]]])
TENSOR

tensor([[[ 1,  2,  4],
         [23,  4,  2],
         [ 2,  4,  2]]])

In [10]:
TENSOR.ndim

3

In [11]:
TENSOR.shape

torch.Size([1, 3, 3])

In [12]:
TENSOR[0,2]

tensor([2, 4, 2])

In [13]:
###  Random Tensor

In [14]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2971, 0.2474, 0.5222, 0.7875],
        [0.0949, 0.0352, 0.7636, 0.6215],
        [0.2208, 0.6981, 0.0792, 0.4509]])

In [15]:
RT = torch.rand(3,8)
RT

tensor([[0.5750, 0.9057, 0.9180, 0.1705, 0.5293, 0.4984, 0.0033, 0.3128],
        [0.5843, 0.0155, 0.9628, 0.3872, 0.2673, 0.7889, 0.6735, 0.8123],
        [0.0966, 0.5206, 0.1502, 0.7132, 0.0318, 0.6353, 0.3034, 0.8751]])

In [16]:
RT.ndim

2

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3 , 224  , 224)) # height , width ,colour change
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [18]:
zeros  = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones = torch.ones(size=(3,4))
ones , ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [20]:
#Creating  range of tensors and tensors-like

In [21]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
one_to_ten = torch.arange(start= 1 , end = 1000 , step = 200 )
one_to_ten

tensor([  1, 201, 401, 601, 801])

In [23]:
# Creating tensors like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

Tensor Datatypes


In [24]:
float_32_tensor = torch.tensor([3.0 , 6.0 ,9.0],
                               dtype = None,
                               device=None,
                               requires_grad=False)
float_32_tensor , float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [27]:
int_32_tensor = torch.tensor([3,7,6] , dtype = torch.int32)
int_32_tensor

tensor([3, 7, 6], dtype=torch.int32)

# Getting information from tensors

1.Tensors not right datatype - to do get datatype from a tensor , can use tensor.dtype
2.Tensors not right shape - to get shape from a tensor , can use tensor.shape
3.Tensors not on the right device - to get device from a tensor , can use tensor.device                                           

In [28]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8646, 0.5535, 0.7495, 0.9166],
        [0.8353, 0.3508, 0.4502, 0.8679],
        [0.2050, 0.7185, 0.9669, 0.9847]])

In [29]:
#find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.8646, 0.5535, 0.7495, 0.9166],
        [0.8353, 0.3508, 0.4502, 0.8679],
        [0.2050, 0.7185, 0.9669, 0.9847]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device tensor is on : cpu


## Manipulation Tensors (tensor operations)

Tensor Opertions include:
* Additions
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [30]:
#Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [31]:
#Multiply Tensor by 10
tensor = tensor *10
tensor

tensor([10, 20, 30])

In [32]:
#Subtract 10
tensor - 10

tensor([ 0, 10, 20])

In [33]:
# Try Out PyTorch in-built Functions
torch.mul(tensor,10)

tensor([100, 200, 300])

In [34]:
torch.sub(tensor , 1000)

tensor([-990, -980, -970])

# Mattrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [35]:
# Element wise multiplication
print(tensor , "*" , tensor)
print(f"Equals : {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals : tensor([100, 400, 900])


In [36]:
#Matix Multiplication
torch.matmul(tensor , tensor)

tensor(1400)

In [37]:
tensor

tensor([10, 20, 30])

In [38]:
# Matrix Multiplication By Hand

1*1 + 2*2 + 3*3

14

In [39]:
# Time

value = 0
for i in range(len(tensor)):
  value += tensor[i] + tensor[i]
print(value)

tensor(120)


In [40]:
#Time
torch.matmul(tensor , tensor)

tensor(1400)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimesnions ** must match:
* (3,2) @ (3,2) wont work
* (2,3) @ (3,2) will work
* (3,2) @ (2,3) will work
@ = Multiplication

torch.matmul(torch.rand(3,2),torch.rand(3,2) Comon Mistake People used to do


2. The resulting matrix has the shape of the **outer dimensions**

(2,3) @ (3,2) --> (2,2)
(3,2) @ (2,3) --> (3,3)

In [41]:
tensor @ tensor

tensor(1400)

In [42]:
 torch.matmul(torch.rand(2,3) , torch.rand(3,2))

tensor([[0.3669, 0.4474],
        [0.9954, 1.3093]])

In [44]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[4,3],
                        [6,5],
                        [8,9]])
#torch.mm(tensor_A , Tensor_B ) # torch.mm is the same as torch.matmul (its and alias for writing less code )
torch.matmul(tensor_A , tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [45]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

TO fix our tensor shape issues , we can manipulate the shape of one of our tensors using a **transpose**.

A **tanspose switches the axes or dimensions of a given tensor



In [46]:
tensor_B.T , tensor_B.T.shape

(tensor([[4, 6, 8],
         [3, 5, 9]]),
 torch.Size([2, 3]))

In [47]:
torch.matmul(tensor_A , tensor_B.T)

tensor([[10, 16, 26],
        [24, 38, 60],
        [38, 60, 94]])

In [49]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes : tensor_A = {tensor_A.shape} , tensor_B = {tensor_B.shape}")
print(f"New shapes : tensor_A = {tensor_A.shape} , tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
output = torch.matmul(tensor_A , tensor_B.T)
print(output)


torch.matmul(tensor_A , tensor_B.T).shape

Original shapes : tensor_A = torch.Size([3, 2]) , tensor_B = torch.Size([3, 2])
New shapes : tensor_A = torch.Size([3, 2]) , tensor_B.T = torch.Size([2, 3])
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
tensor([[10, 16, 26],
        [24, 38, 60],
        [38, 60, 94]])


torch.Size([3, 3])

** FInding the min , max  , mean  , sum  , etc (tensor aggreation )**


In [50]:
#find the min
x = torch.arange(0,100,10)
x , x.dtype


(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [51]:
# Find the min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [52]:
#find the max
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [53]:
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [54]:
# Find the sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

In [55]:
#Finding the Positional min and max


In [56]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
# Find the position in tensor that has the minimum value with argmin() --> return index value
x.argmin()

tensor(0)

In [61]:
#Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [62]:
x[9]

tensor(90)