<a href="https://colab.research.google.com/github/abhish3k4/Deep-learning-Project/blob/main/A_3Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import torch
import pandas as ps
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [15]:
scalar = torch.tensor(13)
scalar.item()

13

In [16]:
scalar.ndim

0

In [17]:
vector = torch.tensor([7,7])
vector
vector.ndim
vector.shape

torch.Size([2])

In [18]:
matrix = torch.tensor([[2,3],[2,6]])
matrix

tensor([[2, 3],
        [2, 6]])

In [19]:
matrix.ndim

2

In [20]:
matrix[1]

tensor([2, 6])

In [21]:
matrix.shape

torch.Size([2, 2])

In [22]:
TENSOR = torch.tensor([[[1,2,4] ,[23,4,2] , [2,4,2]]])
TENSOR

tensor([[[ 1,  2,  4],
         [23,  4,  2],
         [ 2,  4,  2]]])

In [23]:
TENSOR.ndim

3

In [24]:
TENSOR.shape

torch.Size([1, 3, 3])

In [25]:
TENSOR[0,2]

tensor([2, 4, 2])

In [26]:
###  Random Tensor

In [27]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6843, 0.9596, 0.9548, 0.7833],
        [0.8991, 0.0752, 0.2185, 0.8764],
        [0.0240, 0.5259, 0.0314, 0.8162]])

In [28]:
RT = torch.rand(3,8)
RT

tensor([[0.0579, 0.5856, 0.1909, 0.6212, 0.4995, 0.3434, 0.8170, 0.6528],
        [0.7210, 0.0250, 0.8992, 0.6735, 0.8167, 0.4510, 0.8939, 0.2701],
        [0.9721, 0.9042, 0.0181, 0.7857, 0.0351, 0.7631, 0.2735, 0.7080]])

In [29]:
RT.ndim

2

In [30]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3 , 224  , 224)) # height , width ,colour change
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [31]:
zeros  = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
ones = torch.ones(size=(3,4))
ones , ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [33]:
#Creating  range of tensors and tensors-like

In [34]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
one_to_ten = torch.arange(start= 1 , end = 1000 , step = 200 )
one_to_ten

tensor([  1, 201, 401, 601, 801])

In [36]:
# Creating tensors like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

Tensor Datatypes


In [37]:
float_32_tensor = torch.tensor([3.0 , 6.0 ,9.0],
                               dtype = None,
                               device=None,
                               requires_grad=False)
float_32_tensor , float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [38]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [39]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [40]:
int_32_tensor = torch.tensor([3,7,6] , dtype = torch.int32)
int_32_tensor

tensor([3, 7, 6], dtype=torch.int32)

# Getting information from tensors

1.Tensors not right datatype - to do get datatype from a tensor , can use tensor.dtype
2.Tensors not right shape - to get shape from a tensor , can use tensor.shape
3.Tensors not on the right device - to get device from a tensor , can use tensor.device                                           

In [41]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2739, 0.8796, 0.3401, 0.9259],
        [0.9248, 0.3242, 0.5828, 0.3149],
        [0.4452, 0.6402, 0.3000, 0.1688]])

In [42]:
#find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.2739, 0.8796, 0.3401, 0.9259],
        [0.9248, 0.3242, 0.5828, 0.3149],
        [0.4452, 0.6402, 0.3000, 0.1688]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device tensor is on : cpu


## Manipulation Tensors (tensor operations)

Tensor Opertions include:
* Additions
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [43]:
#Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [44]:
#Multiply Tensor by 10
tensor = tensor *10
tensor

tensor([10, 20, 30])

In [45]:
#Subtract 10
tensor - 10

tensor([ 0, 10, 20])

In [46]:
# Try Out PyTorch in-built Functions
torch.mul(tensor,10)

tensor([100, 200, 300])

In [47]:
torch.sub(tensor , 1000)

tensor([-990, -980, -970])

# Mattrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [48]:
# Element wise multiplication
print(tensor , "*" , tensor)
print(f"Equals : {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals : tensor([100, 400, 900])


In [49]:
#Matix Multiplication
torch.matmul(tensor , tensor)

tensor(1400)

In [50]:
tensor

tensor([10, 20, 30])

In [51]:
# Matrix Multiplication By Hand

1*1 + 2*2 + 3*3

14

In [52]:
# Time

value = 0
for i in range(len(tensor)):
  value += tensor[i] + tensor[i]
print(value)

tensor(120)


In [53]:
#Time
torch.matmul(tensor , tensor)

tensor(1400)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimesnions ** must match:
* (3,2) @ (3,2) wont work
* (2,3) @ (3,2) will work
* (3,2) @ (2,3) will work
@ = Multiplication

torch.matmul(torch.rand(3,2),torch.rand(3,2) Comon Mistake People used to do


2. The resulting matrix has the shape of the **outer dimensions**

(2,3) @ (3,2) --> (2,2)
(3,2) @ (2,3) --> (3,3)

In [54]:
tensor @ tensor

tensor(1400)

In [55]:
 torch.matmul(torch.rand(2,3) , torch.rand(3,2))

tensor([[1.1407, 1.3898],
        [1.0402, 1.1671]])

In [56]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[4,3],
                        [6,5],
                        [8,9]])
#torch.mm(tensor_A , Tensor_B ) # torch.mm is the same as torch.matmul (its and alias for writing less code )
torch.matmul(tensor_A , tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape , tensor_B.shape

TO fix our tensor shape issues , we can manipulate the shape of one of our tensors using a **transpose**.

A **tanspose switches the axes or dimensions of a given tensor



In [ ]:
tensor_B.T , tensor_B.T.shape

In [ ]:
torch.matmul(tensor_A , tensor_B.T)

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes : tensor_A = {tensor_A.shape} , tensor_B = {tensor_B.shape}")
print(f"New shapes : tensor_A = {tensor_A.shape} , tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
output = torch.matmul(tensor_A , tensor_B.T)
print(output)


torch.matmul(tensor_A , tensor_B.T).shape

** FInding the min , max  , mean  , sum  , etc (tensor aggreation )**


In [ ]:
#find the min
x = torch.arange(0,100,10)
x , x.dtype


In [ ]:
# Find the min
torch.min(x) , x.min()

In [ ]:
#find the max
torch.max(x) , x.max()

In [ ]:
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

In [ ]:
# Find the sum
torch.sum(x) , x.sum()

In [ ]:
#Finding the Positional min and max


In [ ]:
x

In [ ]:
# Find the position in tensor that has the minimum value with argmin() --> return index value
x.argmin()

In [ ]:
#Find the position in tensor that has the maximum value with argmax()
x.argmax()

In [ ]:
x[9]

In [ ]:
#Reshaping stacking , squeeaing and unsequzing tensors

# Reshaping - reshapes an input tensor to a defined shape
# View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
# Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
# Squeeze - removes all 1 dimensions from a tensor
# Unsqeeze - add a 1 dimension to a target tensor
#permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [61]:
#Let's create tensor
import torch
x = torch.arange(1., 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [62]:
#Add an extra Dimension
x_reshaped = x.reshape(3,4)
x_reshaped , x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [64]:
# Change the view
z = x.view(1,9)
z , z.shape

RuntimeError: shape '[1, 9]' is invalid for input of size 12

In [60]:
# Changing z changes x (Because a view of a tensor shares the same memory as the original )
z[: , 0] =5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [58]:
#stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x] , dim = 1)
x_stacked

tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.],
        [11., 11., 11., 11.],
        [12., 12., 12., 12.]])

In [57]:
#torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [65]:
x_reshaped.shape

torch.Size([3, 4])

In [66]:
x_reshaped.squeeze()

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [67]:
x_reshaped.squeeze().shape

torch.Size([3, 4])

In [69]:
#torch.permute - rearrange teh dimensions of target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [Height , width , colour_channels]

# Permute teh original tensor to rearrange the axis (or dimensions) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1 , 1->2 , 2->0

print(f"Previous shape : {x_original.shape}")
print(f"New shape : {x_permuted.shape}") # [colour_channels , Height , width]

Previous shape : torch.Size([224, 224, 3])
New shape : torch.Size([3, 224, 224])


In [70]:
x_original[0,0,0] = 23
x_original[0,0,0] , x_permuted[0,0,0]

(tensor(23.), tensor(23.))